Fix malformed virglrenderer-a8-shader-swizzle-texture.patch
Remove extra space after '+' marker on line 49 that was causing
compilation error: expected expression.