Fix ANGLE EGL extension include to use eglext.h
The previous patch included eglext_angle.h directly, but that header
requires macros like EGLAPIENTRYP that are defined in eglext.h.

Use #include <EGL/eglext.h> instead, which includes eglext_angle.h
at the end with all proper macros defined. This prevents compilation
errors like:

  error: type specifier missing, defaults to 'int'
  typedef EGLDeviceEXT(EGLAPIENTRYP PFNEGLCREATEDEVICEANGLEPROC)